apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: irentsellbuy-com-tls
spec:
  secretName: irentsellbuy-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: irentsellbuy.com
  dnsNames:
    - irentsellbuy.com
    - www.irentsellbuy.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - irentsellbuy.com
          - www.irentsellbuy.com
