apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  volumeName: postgres-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi